name: 'modern_etl'
version: '1.0.0'
config-version: 2

profile: 'modern_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  modern_etl:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table