from tabulate import tabulate
import json
import re

# Existing rows (we just read the last few to get the width right? No, tabulate recalculates for the whole table)
# Actually, the entire table is auto-generated by run_migration_reference.py.
# If I just generate the row and append it? 
# In grid format, if one row wraps, the whole column width depends on max_content or wrap width!
