"""GENERATED by scripts/generate_pipeline_assets.py from airflow/dags/config/pipelines.yml
Do not edit by hand: run `make generate` after changing the manifest.
"""

CDC_TOPICS = [
    'cdc.public.customers',
    'cdc.public.products',
    'cdc.public.orders',
    'cdc.public.order_items',
]
