#!/usr/bin/env bash
# Generates k8s/01-secrets.generated.yaml with random credentials.
#
# Usage:  bash k8s/generate-secrets.sh
#
# deploy.sh applies the generated file automatically when it exists;
# otherwise it falls back to the well-known defaults in 01-secrets.yaml
# (fine for throwaway test clusters, never for anything shared).
#
# The generated file is gitignored. Keep a copy of the passwords in your
# password manager — regenerating produces new ones, and rotating the DB
# passwords on an existing cluster also requires updating the databases.
set -euo pipefail

OUT="$(cd "$(dirname "$0")" && pwd)/01-secrets.generated.yaml"

rand() {
  # 20 chars of url-safe randomness
  head -c 256 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 20
}

if [ -f "$OUT" ]; then
  echo "Refusing to overwrite existing $OUT"
  echo "Delete it first if you really want new credentials."
  exit 1
fi

cat > "$OUT" <<EOF
# Generated by k8s/generate-secrets.sh — do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: etl-secrets
  namespace: etl
type: Opaque
stringData:
  SOURCE_DB_USER: sourceuser
  SOURCE_DB_PASSWORD: $(rand)
  SOURCE_DB_NAME: sourcedb
  DEST_DB_USER: destuser
  DEST_DB_PASSWORD: $(rand)
  DEST_DB_NAME: destdb
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: $(rand)
  AIRFLOW_ADMIN_USER: admin
  AIRFLOW_ADMIN_PASSWORD: $(rand)
  DASHBOARD_DB_USER: dashboard_ro
  DASHBOARD_DB_PASSWORD: $(rand)
  KAFKA_UI_USER: admin
  KAFKA_UI_PASSWORD: $(rand)
  DASHBOARD_AUTH_USER: admin
  DASHBOARD_AUTH_PASSWORD: $(rand)
EOF

chmod 600 "$OUT"
echo "Wrote $OUT"
echo "deploy.sh will pick it up automatically. Store these passwords safely:"
grep -E 'PASSWORD' "$OUT" | sed 's/^  /  /'
