// GENERATED by scripts/generate_pipeline_assets.py from airflow/dags/config/pipelines.yml
// Do not edit by hand: run `make generate` after changing the manifest.


export interface StoreDef {
  label: string;
  dialect: string;
  tables: Record<string, string>;
  dateTrunc: string;
}

export const STORES: Record<string, StoreDef> = {
  warehouse: {
    label: 'Pipe 1 · warehouse (PostgreSQL)',
    dialect: 'postgresql',
    tables: { customers: 'raw.customers_source', products: 'raw.products_source', orders: 'raw.orders_source', order_items: 'raw.order_items_source' },
    dateTrunc: 'date({})',
  },
  lakehouse: {
    label: 'Pipe 2 · lakehouse (Iceberg via Trino)',
    dialect: 'trino',
    tables: { customers: 'iceberg.lake.customers', products: 'iceberg.lake.products', orders: 'iceberg.lake.orders', order_items: 'iceberg.lake.order_items' },
    dateTrunc: 'cast({} as date)',
  },
  mirror: {
    label: 'Pipe 3 · mirror (ClickHouse)',
    dialect: 'clickhouse',
    tables: { customers: 'mirror.customers_current', products: 'mirror.products_current', orders: 'mirror.orders_current', order_items: 'mirror.order_items_current' },
    dateTrunc: 'toDate({})',
  },
};

export const STORE_NAMES = Object.keys(STORES);
