apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etl-stack.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
      isDefault: true
    - name: PostgreSQL Warehouse
      type: postgres
      url: postgres-dest.{{ .Release.Namespace }}.svc.cluster.local:5432
      database: {{ .Values.secrets.destDb.name }}
      user: {{ .Values.secrets.destDb.user }}
      secureJsonData:
        password: {{ .Values.secrets.destDb.password }}
      jsonData:
        sslmode: disable
