apiVersion: v1
kind: Secret
metadata:
  name: etl-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etl-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  SOURCE_DB_USER: {{ .Values.secrets.sourceDb.user | quote }}
  SOURCE_DB_PASSWORD: {{ .Values.secrets.sourceDb.password | quote }}
  SOURCE_DB_NAME: {{ .Values.secrets.sourceDb.name | quote }}
  DEST_DB_USER: {{ .Values.secrets.destDb.user | quote }}
  DEST_DB_PASSWORD: {{ .Values.secrets.destDb.password | quote }}
  DEST_DB_NAME: {{ .Values.secrets.destDb.name | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.rootPassword | quote }}
  AIRFLOW_ADMIN_USER: {{ .Values.secrets.grafana.adminUser | quote }}
  AIRFLOW_ADMIN_PASSWORD: {{ .Values.secrets.grafana.adminPassword | quote }}
