"""Regenerates every pipeline artifact derived from the manifest
(airflow/dags/config/pipelines.yml):

  - docker/clickhouse/initdb/01_mirror_schema.sql
  - scripts/register_debezium_connector.sh
  - cdc-sync-daemon/cdc_tables.py

Usage (from the repo root):  python scripts/generate_pipeline_assets.py
CI runs this and fails if the committed artifacts differ.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / 'airflow' / 'dags'))

import pipeline_config as pc  # noqa: E402

HEADER = '-- GENERATED by scripts/generate_pipeline_assets.py from airflow/dags/config/pipelines.yml\n-- Do not edit by hand: run `make generate` after changing the manifest.\n'


def gen_clickhouse(manifest):
    prefix = manifest.get('topic_prefix', 'cdc')
    schema = manifest.get('source_schema', 'public')
    out = [HEADER]
    out.append('''--
-- Columnar hot mirror fed from the Debezium CDC topics.
-- Pattern per table:
--   kafka_<t>   Kafka engine table reading the topic as raw JSON
--   <t>         ReplacingMergeTree(ver, is_deleted) — latest version wins
--   <t>_mv      materialized view parsing the Debezium envelope
--   <t>_current clean read view (collapsed, deletes filtered)
--
-- Runs on first boot of a fresh ClickHouse volume. For an existing volume:
--   docker exec -i clickhouse clickhouse-client --multiquery < docker/clickhouse/initdb/01_mirror_schema.sql

CREATE DATABASE IF NOT EXISTS mirror;
''')

    for name, table in manifest['tables'].items():
        cols = table['columns']
        width = max(len(c) for c in cols) + 1
        col_defs = '\n'.join(
            f"    {c.ljust(width)}{pc.clickhouse_type(name, table, c)},"
            for c in cols
        )
        extracts = '\n'.join(
            f"    {pc.clickhouse_extract(table, c)} AS {c},"
            for c in cols
        )
        topic = f"{prefix}.{schema}.{name}"
        group = f"clickhouse-mirror-{name.replace('_', '-')}"
        out.append(f'''-- ── {name} ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mirror.{name}
(
{col_defs}
    {'ver'.ljust(width)}UInt64,
    {'is_deleted'.ljust(width)}UInt8
)
ENGINE = ReplacingMergeTree(ver, is_deleted)
ORDER BY {table['primary_key']};

CREATE TABLE IF NOT EXISTS mirror.kafka_{name} (raw String)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:9092',
         kafka_topic_list = '{topic}',
         kafka_group_name = '{group}',
         kafka_format = 'JSONAsString';

CREATE MATERIALIZED VIEW IF NOT EXISTS mirror.{name}_mv TO mirror.{name} AS
WITH
    JSONExtractString(raw, 'op') AS op,
    if(op = 'd', JSONExtractRaw(raw, 'before'), JSONExtractRaw(raw, 'after')) AS rec
SELECT
{extracts}
    JSONExtractUInt(raw, 'ts_ms') AS ver,
    if(op = 'd', 1, 0) AS is_deleted
FROM mirror.kafka_{name}
WHERE length(raw) > 0 AND rec NOT IN ('', 'null');

CREATE VIEW IF NOT EXISTS mirror.{name}_current AS
SELECT * EXCEPT (ver, is_deleted) FROM mirror.{name} FINAL WHERE is_deleted = 0;
''')  # nosec B608 - code generator emitting SQL from the manifest, not runtime queries
    return '\n'.join(out)


def gen_connector_script(manifest):
    include_list = pc.table_include_list(manifest)
    first_table = next(iter(manifest['tables']))
    prefix = manifest.get('topic_prefix', 'cdc')
    schema = manifest.get('source_schema', 'public')
    sink_topic = f"{prefix}.{schema}.{first_table}"
    sink_pk = manifest['tables'][first_table]['primary_key']
    return f'''#!/usr/bin/env bash
# GENERATED by scripts/generate_pipeline_assets.py from airflow/dags/config/pipelines.yml
# Do not edit by hand: run `make generate` after changing the manifest.
#
# Registers the Debezium PostgreSQL connector with Kafka Connect.
# Run once after `make up` and the stack is healthy.
# Usage: bash scripts/register_debezium_connector.sh

set -euo pipefail

# Default to Docker Compose name; in K8s set KAFKA_CONNECT_URL=http://kafka-connect.etl.svc.cluster.local:8083
CONNECT_URL="${{KAFKA_CONNECT_URL:-http://kafka-connect:8083}}"

SOURCE_DB_HOST="${{SOURCE_DB_HOST:-postgres-source}}"
SOURCE_DB_PORT="${{SOURCE_DB_PORT:-5432}}"
SOURCE_DB_USER="${{SOURCE_DB_USER:-sourceuser}}"
SOURCE_DB_PASSWORD="${{SOURCE_DB_PASSWORD:-sourcepass}}"
SOURCE_DB_NAME="${{SOURCE_DB_NAME:-sourcedb}}"

echo "Waiting for Kafka Connect to be ready..."
until curl -sf "${{CONNECT_URL}}/connectors" > /dev/null; do
  echo "  ... not ready yet, retrying in 5s"
  sleep 5
done
echo "Kafka Connect is ready."

# Check if connector already exists
if curl -sf "${{CONNECT_URL}}/connectors/orders-cdc-connector" > /dev/null 2>&1; then
  echo "Connector 'orders-cdc-connector' already exists. Delete it first to re-register:"
  echo "  curl -X DELETE ${{CONNECT_URL}}/connectors/orders-cdc-connector"
  exit 0
fi

echo "Registering Debezium PostgreSQL connector..."

curl -X POST "${{CONNECT_URL}}/connectors" \\
  -H "Content-Type: application/json" \\
  -d "{{
    \\"name\\": \\"orders-cdc-connector\\",
    \\"config\\": {{
      \\"connector.class\\": \\"io.debezium.connector.postgresql.PostgresConnector\\",
      \\"database.hostname\\": \\"${{SOURCE_DB_HOST}}\\",
      \\"database.port\\": \\"${{SOURCE_DB_PORT}}\\",
      \\"database.user\\": \\"${{SOURCE_DB_USER}}\\",
      \\"database.password\\": \\"${{SOURCE_DB_PASSWORD}}\\",
      \\"database.dbname\\": \\"${{SOURCE_DB_NAME}}\\",
      \\"topic.prefix\\": \\"{prefix}\\",
      \\"table.include.list\\": \\"{include_list}\\",
      \\"plugin.name\\": \\"pgoutput\\",
      \\"slot.name\\": \\"debezium_orders_slot\\",
      \\"publication.name\\": \\"debezium_orders_pub\\",
      \\"snapshot.mode\\": \\"initial\\",
      \\"decimal.handling.mode\\": \\"double\\"
    }}
  }}"

echo ""
echo "Registering Postgres JDBC Sink connector..."

curl -X POST "${{CONNECT_URL}}/connectors" \\
  -H "Content-Type: application/json" \\
  -d "{{
    \\"name\\": \\"orders-jdbc-sink\\",
    \\"config\\": {{
      \\"connector.class\\": \\"io.debezium.connector.jdbc.JdbcSinkConnector\\",
      \\"tasks.max\\": \\"1\\",
      \\"topics\\": \\"{sink_topic}\\",
      \\"connection.url\\": \\"jdbc:postgresql://${{DEST_DB_HOST:-postgres-dest}}:${{DEST_DB_PORT:-5432}}/${{DEST_DB_NAME:-destdb}}\\",
      \\"connection.username\\": \\"${{DEST_DB_USER:-destuser}}\\",
      \\"connection.password\\": \\"${{DEST_DB_PASSWORD:-destpass}}\\",
      \\"insert.mode\\": \\"upsert\\",
      \\"delete.enabled\\": \\"true\\",
      \\"primary.key.mode\\": \\"record_key\\",
      \\"primary.key.fields\\": \\"{sink_pk}\\",
      \\"table.name.format\\": \\"{schema}.{first_table}\\"
    }}
  }}"

echo ""
echo "Connectors registered. Check status with:"
echo "  curl ${{CONNECT_URL}}/connectors/orders-cdc-connector/status | jq ."
echo "  curl ${{CONNECT_URL}}/connectors/orders-jdbc-sink/status | jq ."
'''


def gen_daemon_tables(manifest):
    lines = ',\n'.join(f"    '{t}'" for t in pc.topics(manifest))
    return f'''"""GENERATED by scripts/generate_pipeline_assets.py from airflow/dags/config/pipelines.yml
Do not edit by hand: run `make generate` after changing the manifest.
"""

CDC_TOPICS = [
{lines},
]
'''


def main():
    manifest = pc.load_manifest(str(REPO / 'airflow' / 'dags' / 'config' / 'pipelines.yml'))

    targets = {
        REPO / 'docker' / 'clickhouse' / 'initdb' / '01_mirror_schema.sql': gen_clickhouse(manifest),
        REPO / 'scripts' / 'register_debezium_connector.sh': gen_connector_script(manifest),
        REPO / 'cdc-sync-daemon' / 'cdc_tables.py': gen_daemon_tables(manifest),
    }

    check = '--check' in sys.argv
    dirty = []
    for path, content in targets.items():
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current != content:
            if check:
                dirty.append(str(path.relative_to(REPO)))
            else:
                path.write_text(content, encoding='utf-8', newline='\n')
                print(f"wrote {path.relative_to(REPO)}")

    if check and dirty:
        print('Out of sync with airflow/dags/config/pipelines.yml:')
        for d in dirty:
            print(f'  {d}')
        print('Run: python scripts/generate_pipeline_assets.py')
        sys.exit(1)
    if check:
        print('All generated artifacts are in sync.')


if __name__ == '__main__':
    main()
